// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0EBSDl8Hbp5bzBI0tv8Q-6G5EKQvA_I',
    appId: '1:875573875329:web:786518fa5616b95d5a7380',
    messagingSenderId: '875573875329',
    projectId: 'whatsapp-740e8',
    authDomain: 'whatsapp-740e8.firebaseapp.com',
    storageBucket: 'whatsapp-740e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0sjzXtIS9e_FVf1tngNzGNroP48uDBY',
    appId: '1:875573875329:android:2208f55133017b1d5a7380',
    messagingSenderId: '875573875329',
    projectId: 'whatsapp-740e8',
    storageBucket: 'whatsapp-740e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzkh32lsW6OHlqREETQ_mZaE8BpTXGm8',
    appId: '1:875573875329:ios:4f083bef78df09d65a7380',
    messagingSenderId: '875573875329',
    projectId: 'whatsapp-740e8',
    storageBucket: 'whatsapp-740e8.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClonee',
  );
}
